# Disable UART console — we use RTT instead (frees UART0 for VW101)
CONFIG_UART_CONSOLE=n
CONFIG_LOG_BACKEND_UART=n

# RTT for logging
CONFIG_USE_SEGGER_RTT=y
CONFIG_LOG_BACKEND_RTT=y
CONFIG_RTT_CONSOLE=y

CONFIG_SERIAL=y
CONFIG_CONSOLE=n

CONFIG_LOG=y